baseURL = 'https://huaoyan.top/'
locale = 'zh-cn'
title = "Huaoyan's Blog"
theme = 'github.com/adityatelange/hugo-PaperMod'

[module]
  [[module.imports]]
    path = 'github.com/adityatelange/hugo-PaperMod'
